theme: osuny
_merge: deep
params:
  breadcrumb:
    position: hero-end
  summary:
    position: content
  search:
    active: false
  logo:
    header: '/assets/images/logo-v2.svg'
    footer: '/assets/images/icon-v2.svg'
  menu:
    primary:
      level_2:
        title:
          active: true
  projects:
    index:
      layout: list