theme: osuny
_merge: deep
params:
  breadcrumb:
    position: hero-end
  summary:
    position: content
  search:
    active: false
  logo:
    header: '/assets/images/logo-v2.svg'
    footer: '/assets/images/icon-v2.svg'
  projects:
    index:
      layout: list
  image_sizes:
    blocks:
      projects:
        grid:
          desktop:  555